### ISSUE TITLE
Running tests

### ISSUE THREAD

**Issue by XinyuLiu5566** [KnugiHK/synapse-admin-api-python#4]
When i was trying to run the tests to find if there were any flaky tests in the project I got the error saying that "no such file or directory: 'synapse_test/admin.token'". Just wondering where this file locates.

**Comment by KnugiHK** [comment]
I assume you run "testing_env.sh" in the root of this repo. The file should be located in /{root of this repo}/synapse_test/admin.token

**Comment by XinyuLiu5566** [comment]
I was trying to run the tests to see if there were any flaky tests there and encountered this problem.  I didn't run the _testing_env.sh_ file, do I have to run it before testing?

**Comment by KnugiHK** [comment]
Yes. The script will set up the environment needed for unit tests (installing & configuring Synapse) and run the test automatically.
